pipeline {
    agent any
    stages{
        stage('Test'){
            steps{
               echo 'hello-jenkins!!'
            }
        }
        stage('Python installation'){
            steps{
                sh 'apt install python3 -y'
            }
        }
    }

}