pipeline {
    agent {
          docker { image 'node:16-alpine' }
    }
    stages{
        stage('Test'){
            steps{
               echo 'hello-jenkins!!'
            }
        }
        stage('apache installation'){
            steps{
                sh 'node --version'
            }
        }
    }

}