pipeline {
    agent any
    stages{
        stage('Test'){
            steps{
               echo 'hello-jenkins!!'
            }
        }
        stage('apache installation'){
            steps{
                sh 'python --version'
            }
        }
    }

}