---
name : Installing apache server on the node Instance
hosts : all
become: true

tasks:
  - name : Installing apache server
    apt:
      name : apache2
      state : present

  - name : Restarting the apache server
    notify:
      name : apache2
      state : started