- name: Installation of python latest
  hosts: all
  become: true
  tasks:
   - name: python  installation
     ansible.builtin.yum:
      name: python3
      state: installed
- name: Installation of Nginx
  hosts: WEB
  become: true
  roles:
    - first-role