- name: Working on the conditions in ansible playbook
  hosts: WEB
  become: true
  vars:
    fruit1: true
    fruit2: carrot
  tasks:
    - name: print the fruit name
      ansible.builtin.debug:
        msg: fruit name - mango
      when: fruit1 is false

    - name: print the Vegetable name
      ansible.builtin.debug:
        msg: fruit name - bottle-guard
      when: fruit2 == "carrot"

    - name: Nginx installation check
      ansible.builtin.shell:
        cmd: yum list installed | grep ^nginx
      register: nginx_check

    - name: print the Vegetable name
      ansible.builtin.debug:
        msg: fruit name - " {{ nginx_check }} "

    - name: Ignore errors check
      ansible.builtin.shell:
        cmd: yum install python -y
      ignore_errors: yes