- name: Working on the conditions in ansible playbook
  hosts: WEB
  become: true
  vars:
    fruit1: true
    fruit2: carrot
  tasks:
    - name: print the fruit name
      ansible.builtin.debug:
        msg: fruit name - mango
      when: fruit1 is false

    - name: print the Vegetable name
      ansible.builtin.debug:
        msg: fruit name - bottle-guard
      when: fruit2 == "carrot"