- name: demo of ansible data types
  hosts: localhost
  become: true
  vars:
    num: 12
    fruits: "mango"
    boo: true
  tasks:
    - name: data type printing
      ansible.builtin.debug:
        msg: number - {{ num }}, fruit_name - {{ fruits }}
      when: "{{ boo }}"