---
- name: working on playbook to create vars and debug
  hosts: all
  become: true
  vars:
    sample1=Hello-world
    g20=welcome to g20 summit INDIA
  tasks:
    - name: working on debug and variables of ansible
      ansible.builtin.debug:
        msg: {{ sample1,g20  }}

