---
- name: Install and start of nginx playbook
  hosts: WE
  become: true

  tasks:
    - name: Installation of nginx server
      yum:
        name : nginx
        state : present

    - name: Service nginx
      service:
        name: nginx
        state: started

- name: Install and setup mongo DB
  hosts: Mongo
  become: true

  tasks:
    - name: Installing of Mongo DB server
      yum:
        name : mongod
        state: present


