- name: loops in ansible
  become: true
  hosts: localhost
  vars:
    fruits:
      - orange
      - apple
      - mango
  tasks:
    - name: Iteration of fruits
      ansible.builtin.debug:
        msg: fruits name - "{{ item }}"
      loop: "{{ fruits }}"