- name: data types in ansible
  hosts: localhost
  become: true
  vars:
    fruits:
      - mango
      - orange
  tasks:
    name: printing the values in loops
    ansible.builtin.debug:
      msg: fruits_name - {{ item }}
      loop: "{{ fruits }}"

      name: printing sub values also
      ansible.builtin.debug:
        msg: veg name - {{ item.name }},quantity - {{ quantity.name }}
        loop:
          - { name: "potato" , quantity: 100 }
          - { name: "tomato" , quantity: 200 }