- name: play level variables demo
  become: true
  hosts: localhost
  vars:
    a_name: play.level.com
  tasks:
    - name: Access play level variable
      ansible.builtin.debug:
        msg: play level variable {{ a_name }}

    - name: Access local level variable
      ansible.builtin.debug:
        msg: play level variable {{ local_name }}
      vars:
        local_name: local.level.com