---
- name : Working on second playbook of ansible.
  hosts : all
  become : true

  tasks:
    - name : File creation using shell
      shell : touch sample-file.txt
    - name : creating a directory
      shell : mkdir demo1
    - name : copying the file to the dir
      copy :
        src: /home/centos/*
        dest: /home/centos/demo1/
