- name: Copying the service file to desired location
  ansible.builtin.copy:
    src: service/catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Restarting the catalogue services
  ansible.builtin.systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: true