- name: Setup of Catalogue service for roboshop
  hosts: CATALOGUE
  become: true
  tasks:
    - name: Setting Node JS repo
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: Installation of Node JS
      ansible.builtin.yum:
        name: nodejs
        state: present

    - name: Adding roboshop user
      ansible.builtin.user:
        name: roboshop

    - name: Cleaning old app content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Creating app dir
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Unzipping the catalogue file provided by dev team
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
        dest: app
        remote_src: yes

    - name: Changing the dir and working on npm install
      ansible.builtin.shell: npm install
      args:
        chdir: app/

    - name: Copying the data of catalogue service to systemd service file
      ansible.builtin.copy:
        src: service/catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Restarting the system service for the catalogue
      ansible.builtin.systemd:
        name: catalogue
        enabled: yes
        state: started
        daemon-reload: true

    - name: Setting up the mongo-db schema
      ansible.builtin.import_tasks:
        file: mongo-schema.yaml




