- name: playbook for the catalogue robo shop application
  hosts: CATALOGUE
  become: true
  tasks:
    - name: setting node JS function
      ansible.builtin.import_tasks:
        file: nodejs-setup.yaml

    - name: Adding robo-shop user
      ansible.builtin.user:
        name: roboshop

    - name: setting database schema of roboshop project
      ansible.builtin.import_tasks:
        file: mongo-schema.yaml

    - name: Downloading catalogue zip file and extracting the content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Setup of catalogue robo-shop application
      ansible.builtin.import_tasks:
        file: catalogue_system.yaml