- name: Installation of nginx web server
  hosts: WEB
  become: true

  tasks:
    - name: Installing nginx web server
      ansible.builtin.yum:
        name: nginx
        state: installed
    - name: Copying roboshop conf file
      ansible.builtin.copy:
        src: config/roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf
    - name: Remove default web server of nginx
      ansible.builtin.file:
        path: /usr/share/nginx/html/*
        state: absent
    - name: Downloading web frontend zip file
      ansible.builtin.file:
        path: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        state: hard
    - name: changing the directory and unzipping the frontend
      ansible.builtin.shell:
        chdir: /usr/share/nginx/html
        cmd: unzip /tmp/frontend.zip &>> /dev/null
    - name: Restarting of nginx web service
      ansible.builtin.service:
        name: nginx
        enabled: true
        state: started


