- name: Installation of Mongo DB schema
  hosts: CATALOGUE
  become: true

  tasks:
    - name: Copying the mongo db repo file
      ansible.builtin.copy:
        src: config/mongod.repo
        dest: /etc/yum.repos.d/mongo.repo
    - name: Installation of Mongo DB application
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed