- name: Downloading the node JS file
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installation of the Node JS Application
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Cleaning old app dir
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating app dir
  ansible.builtin.file:
    path: /app
    state: directory

- name: changing the app directory
  ansible.builtin.shell: cd /app

- name: Installation of npm
  ansible.builtin.shell: npm install