- name: Adding the roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Removing the app dir
  ansible.builtin.file:
    name: /app
    state: absent

- name: Creating the app dir
  ansible.builtin.file:
    name: /app
    state: directory

- name: Downloading the zip file
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/payment.zip
    dest: /app
    remote_src: yes

- name: Downloading the pip3 requirements
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app