- name: Creating playbook for the payment application
  hosts: PAYMENT
  become: true

  tasks:
    - name: Installation of python application
      ansible.builtin.yum:
        name:
          - python36
          - gcc
          - python3-devel
        state: installed

    - name: Creating application playbook
      ansible.builtin.import_tasks: payment_appreq.yaml

    - name: Copying the payment service file
      ansible.builtin.copy:
        src: service/payment.service
        dest: /etc/systemd/system/payment.service

    - name: Restarting the payment service
      ansible.builtin.systemd:
        name: payment
        state: restarted
        enabled: yes
        daemon-reload: yes