- name: Playbook for rabbitMQ application
  hosts: RABBITMQ
  become: true
  vars:
    rabbit_comp: rabbitmq-server
  tasks:
    - name: Downloading the rabbit-erlang repos
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

    - name: Downloading the rabbit-server repos
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: Installing rabbit-MQ server
      ansible.builtin.yum:
        name: "{{ rabbit_comp }}"
        state: installed

    - name: Setting user name and permission
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present

    - name: Restarting rabbit-mq servers
      ansible.builtin.systemd:
        name: "{{ rabbit_comp }}"
        enabled: yes
        state: restarted
