- name: Playbook for rabbitMQ application
  hosts: RABBITMQ
  become: true
  vars:
    rabbit_comp: rabbit-server
  tasks:
    - name: Downloading the rabbit-er
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

    - name: Downloading the rabbit-er
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

    - name: Installing rabbit-MQ server
      ansible.builtin.yum:
        name: "{{ rabbit_comp }}"
        state: installed

    - name: Setting the rabbit-MQ user-name
      ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

    - name: Setting the rabbit-MQ password
      ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

    - name: Restarting rabbit-mq servers
      ansible.builtin.systemd:
        name: "{{ rabbit_comp }}"
        enabled: yes
        state: restarted
