- name: Redis Roboshop playbook
  hosts: REDIS
  become: true
  tasks:
    - name: Install Redis for roboshop
      ansible.builtin.yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: present