- name: playbook for the shipping component of roboshop
  hosts: SHIP
  become: true
  vars:
    maven_1: maven
    mysql_1: mysql
  tasks:
    - name: Installation of maven
      ansible.builtin.yum:
        name: "{{ maven_1 }}"
        state: installed

    - name: Adding application requirements.
      ansible.builtin.import_tasks: shipping_appreq.yaml

    - name: Cleaning maven package
      ansible.builtin.shell: mvn clean package ; mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: app

    - name: my-sql database application
      ansible.builtin.import_tasks: mysql_setup.yaml

    - name: Restart the service of shipping application
      ansible.builtin.import_tasks: shipping_service.yaml

