- name: Copying of shipping service file
  ansible.builtin.copy:
    src: service/shipping.service
    dest: /etc/systemd/system/shipping.service

- name: Restarting the services of shipping
  ansible.builtin.systemd:
    name: shipping
    state: restarted
    enabled: yes
    daemon-reload: yes