- name: User application playbook
  hosts: USER
  become: true
  vars:
    component: user
  tasks:
    - name: Node JS setup
      ansible.builtin.import_tasks: nodejs-setup.yaml

    - name: setting up the application pre-requirements
      ansible.builtin.import_tasks: appreq_user.yaml

    - name: setting database schema of roboshop project
      ansible.builtin.import_tasks: mongo-schema.yaml

    - name: Restarting the User application
      ansible.builtin.import_tasks: user_system.yaml