- name: Copying the content of service file
  ansible.builtin.copy:
    src: roboshop-ansible/service/payment.service
    dest: /etc/systemd/system/payment.service

- name: Restarting the payment service.
  ansible.builtin.systemd:
    name: payment
    daemon-reload: true
    enabled: yes
    state: restarted