- name: installation of maven
  ansible.builtin.yum:
    name: "{{ maven_app }}"
    state: installed

- name: Adding robo-shop user
  ansible.builtin.user:
    name: roboshop

- name: Import shipping app role
  ansible.builtin.import_role:
    name: "{{ component }}"
    tasks_from: "{{ ship_app }}"

- name: Import shipping mysql role
  ansible.builtin.import_role:
    name: "{{ component }}"
    tasks_from: "{{ ship_mysql }}"

- name: Copy of the "{{ component }}" service file
  ansible.builtin.copy:
    src: service/"{{ component }}".service
    dest: /etc/systemd/system/"{{ component }}".service

- name: Restarting of "{{ component }}" services
  ansible.builtin.systemd:
    name: "{{ component }}"
    daemon-reload: true
    enabled: yes
    state: restarted