- name: Installation of mysql
  ansible.builtin.yum:
    name: "{{ mysql_app }}"
    state: installed

- name: Loading mysql to server
  ansible.builtin.shell: mysql -h mysql.srilearndevops.online -uroot -pRoboShop@1 < /app/schema/"{{ component }}".sql