#Adding the base image
FROM ubuntu:latest

#Now let us add the working dir
WORKDIR /app

#Let is copy  the content to /app directory
COPY . /app

ARG Build_number
ENV build_number=${Build_number}

#Install the required packages to run the docker python script.
RUN apt-get update && apt-get install zip -y && apt install nginx 
