- name: Copying the mongo db repo file
  ansible.builtin.copy:
    src: config/mongod.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Installation of mongo-db server
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Replacing the Listen Address of MongoDB
  ansible.builtin.replace:
    path: /etc/{{ file_name }}.conf
    regexp: 127.0.0.1
    replace: 0.0.0.0

- name: Starting the mongo-db service
  ansible.builtin.service:
    name: "{{ file_name }}"
    state: restarted